// LOCALHOST 
### Get all tasks
GET http://localhost:3000/tasksSwagger/get-all

### get task by id
GET http://localhost:3000//tasksSwagger/get-single/62ad6766d56f7b889ffefc6f


### create task
POST http://localhost:3000/tasksSwagger/ceate HTTP/1.1
content-type: application/json

{
  "task":"Mop the Floor",
  "location": "Dining Room",
  "startTime": "4:45pm",
  "startDate": "8/28/22",
  "deadlineDate": "8/28/22",
  "deadlineTime": "5:30pm"
}

### Put task (edit)
PUT http://localhost:3000/tasksSwagger/edit/62ad691fd56f7b889ffefc94 HTTP/1.1
content-type: application/json

{
  "task": "Pick Up Mail",
  "location": "Post Office",
  "startTime": "2:00pm",
  "startDate": "7/22/22",
  "deadlineDate": "7/23/22",
  "deadlineTime": "5:00pm"
}

### Delete task
DELETE http://localhost:3000/tasksSwagger/delete/62ad691fd56f7b889ffefc94



// HEROKU

### Get all tasks
GET https://cse341apitodo.herokuapp.com/tasksSwagger/get-all

### get task by id
GET https://cse341apitodo.herokuapp.com/get-single/62ad6766d56f7b889ffefc6f

### create task
POST https://cse341apitodo.herokuapp.com/tasksSwagger/ceate HTTP/1.1
content-type: application/json

{
  "task":"Sweep the Floor",
  "location": "Dining Room",
  "startTime": "3:45pm",
  "startDate": "8/28/22",
  "deadlineDate": "8/28/22",
  "deadlineTime": "4:30pm"
}

### Put task (edit)
PUT https://cse341apitodo.herokuapp.com/tasksSwagger/edit/62ad691fd56f7b889ffefc94 HTTP/1.1
content-type: application/json

{
  "task": "Soccer Game",
  "location": "Porter Park",
  "startTime": "8:30am",
  "startDate": "6/24/22",
  "who": "Joe",
  "deadlineDate": "6/24/22",
  "deadlineTime": "10:30am"
}

### Delete task
DELETE https://cse341apitodo.herokuapp.com/tasksSwagger/delete/62ad691fd56f7b889ffefc94


// USER

// LOCALHOST 
### Get all Users
GET http://localhost:3000/user/get-all

### get user by id
GET http://localhost:3000/user/get-single/62ad691fd56f7b889ffefc94


### create user
POST http://localhost:3000/user/ceate HTTP/1.1
content-type: application/json

{
  "googleId": "111009140578123232112",
  "displayName": "Test User",
  "firstName": "Test",
  "lastName": "User",
  "image": "Dan",
  "createdAt": "8/28/22"
}

### Put user (edit)
PUT http://localhost:3000/user/edit/62ad691fd56f7b889ffefc94 HTTP/1.1
content-type: application/json

{
  "googleId": "111009140578123232112",
  "displayName": "Testing",
  "firstName": "Test",
  "lastName": "User",
  "image": "Dan",
  "createdAt": "8/28/22"
}

### Delete task
DELETE http://localhost:3000/user/delete/62ad691fd56f7b889ffefc94

// HEROKU
### Get all Users
GET https://cse341apitodo.herokuapp.com/user/get-all

### get user by id
GET https://cse341apitodo.herokuapp.com/get-single/62ad691fd56f7b889ffefc94


### create user
POST https://cse341apitodo.herokuapp.com/user/ceate HTTP/1.1
content-type: application/json

{
  "googleId": "111009140578123232112",
  "displayName": "Test User",
  "firstName": "Test",
  "lastName": "User",
  "image": "Dan",
  "createdAt": "8/28/22"
}

### Put user (edit)
PUT https://cse341apitodo.herokuapp.com/user/edit/62ad691fd56f7b889ffefc94 HTTP/1.1
content-type: application/json

{
  "googleId": "111009140578123232112",
  "displayName": "Testing",
  "firstName": "Test",
  "lastName": "User",
  "image": "Dan",
  "createdAt": "8/28/22"
}

### Delete task
DELETE https://cse341apitodo.herokuapp.com/user/delete/62ad691fd56f7b889ffefc94