// LOCALHOST 
### Get all tasks
GET http://localhost:3000/tasks

### get task by id
GET http://localhost:3000/tasks/62882223328190b287b14755


### create task
POST http://localhost:3000/tasks HTTP/1.1
content-type: application/json

{
  "task":"Mop the Floor",
  "location": "Dining Room",
  "startTime": "4:45pm",
  "startDate": "8/28/22",
  "who": "Dan",
  "deadlineDate": "8/28/22",
  "deadlineTime": "5:30pm"
}

### Put task (edit)
PUT http://localhost:3000/tasks/62882223328190b287b14750 HTTP/1.1
content-type: application/json

{
  "task": "Pick Up Mail",
  "location": "Post Office",
  "startTime": "1:00pm",
  "startDate": "7/22/22",
  "who": "Marry",
  "deadlineDate": "7/23/22",
  "deadlineTime": "5:00pm"
}

### Delete task
DELETE http://localhost:3000/tasks/62882a6a3319020e178bc659



// HEROKU

### Get all tasks
GET https://cse341apitodo.herokuapp.com/tasks

### get task by id
GET https://cse341apitodo.herokuapp.com/tasks/62882223328190b287b14751

### create task
POST https://cse341apitodo.herokuapp.com/tasks HTTP/1.1
content-type: application/json

{
  "task":"Sweep the Floor",
  "location": "Dining Room",
  "startTime": "3:45pm",
  "startDate": "8/28/22",
  "who": "Baden",
  "deadlineDate": "8/28/22",
  "deadlineTime": "4:30pm"
}

### Put task (edit)
PUT https://cse341apitodo.herokuapp.com/tasks/62882223328190b287b14753 HTTP/1.1
content-type: application/json

{
  "task": "Soccer Game",
  "location": "Porter Park",
  "startTime": "8:30am",
  "startDate": "6/24/22",
  "who": "Brian",
  "deadlineDate": "6/24/22",
  "deadlineTime": "10:30am"
}

### Delete contact 
DELETE https://cse341apitodo.herokuapp.com/tasks/62882e4e92e3096f73da2500
